[LIVE_FOOTBALL_INFORMATION]
URL_MAIN = https://www.livefutbol.com
COUNTRIES_AND_FEDERATIONS = Alemania,Argentina,Brasil,Colombia,CONMEBOL,España,FIFA,Francia,Inglaterra,Italia,UEFA
COMPETITIONS_SECTIONS = Calendario,Equipos,Resultados y Clasificaciones
TEAMS_SECTION = Equipos
CALENDAR_SECTION = Calendario
RESULTS_AND_STANDINGS_SECTION = Resultados y Clasificaciones
TEAMS_SECTIONS = Fechas y resultados,Historial contra...
DATES_AND_RESULTS_SECTION = Fechas y resultados
H2H_SECTION = Historial contra...
SESSION_TYPES = CALENDAR_YEAR,MID_CALENDAR_YEAR

[LF_SELECTORS]
COUNTRIES_OR_FEDERATIONS = nav.hs-menu-level-main select.hs-menu--list option
COMPETITIONS = nav.hs-menu-level-main div.module-menu:nth-of-type(2) select.hs-menu--list option
COMPETITIONS_SECTIONS = nav.hs-menu-level-sub.hs-menu-level-competition ul.hs-menu--list li a.hs-menu--item-link
CALENDAR = div.hs-teams div.module-teams td.team-name_extended a
CALENDAR_GAME_PLAN = div.module-gameplan
CALENDAR_HEADING = div.hs-head--round, div.competition-head, div.round-head
CALENDAR_MATCH = div.match
CALENDAR_MATCH_DATE = div.match-date, td.match-date
CALENDAR_MATCH_TIME = div.match-time
CALENDAR_HOME_TEAM = div.team-name-home, div.team-name
CALENDAR_AWAY_TEAM = div.team-name-away
TEAMS = div.hs-teams div.module-teams td.team-name_extended a
TEAMS_SECTIONS = nav.hs-menu-level-sub.hs-menu-level-team ul.hs-menu--list li a
COACHING_HISTORY_TABLE = div.hs-persons table tbody tr:has(td.team_person-period)
COACH_PERIOD = td.team_person-period
COACH_NAME = td.person-name a
SESSIONS_SELECT_TEAM = div.hs-select div.module-select select.navigation.season-navigation option
MATCHES_LIST = div.module-gameplan tr
CLASS = class
ROW_CLASS_COMPETITION_HEAD = competition-head
ROW_CLASS_MATCH = match
ROW_TH_A = th a
ROW_TD_MATCH_DATE = td.match-date
ROW_TD_MATCH_RESULT_ALL = td.match-result-all
ROW_TD_MATCH_RESULT_ALL_A = td.match-result-all a
ROW_TD_MATCH_RESULT_TENDENCY = td.match-tendency
ROW_TD_MATCH_SHORTNAME_EXTENDED_A = td.team-shortname_extended a
ROW_TD_MATCH_VENUE = td.match-homeaway
STATUS_MATCH_FINISHED = finished
STATUS_MATCH_UPCOMING = upcoming
STATUS_MATCH_TO_ANALYZE = to analyze

[FIFA-Copa Mundial]
WORLD_RANKING_URL = https://www.livefutbol.com/fifa-world-ranking/fe1/
LF_SELECTOR_STANDING = table.module-ranking

[FIFA-Mundial de Clubes]
WORLD_RANKING_URL = To Define
LF_SELECTOR_STANDING = To Define

[LIGA-STANDARD]
COMPETITIONS = Alemania-Bundesliga,Brasil-Série A,España-Primera División,Francia-Ligue 1,Inglaterra-Premier League,Italia-Serie A
LF_SELECTOR_STANDING = div.module-standing
;TODO Create selectors to home and away standings

[LIGA-ARGENTINA]
COMPETITIONS = Superliga Argentina
LF_SELECTOR_STANDING = div.module-standing
;TODO Create selectors to home and away standings
;TODO Create selectors to next rounds

[LIGA-COLOMBIA]
COMPETITIONS = Colombia-Primera A
LF_SELECTOR_STANDING = div.module-standing
;TODO Create selectors to home and away standings
;TODO Create selectors to next rounds

[NATIONAL-TEAM-CUP]
COMPETITIONS = CONMEBOL-Copa América,UEFA-Eurocopa
LF_SELECTOR_STANDING = div.module-standing
;TODO Create selectors to home and away standings
;TODO Create selectors to next rounds

[CONTINENTAL-CLUB-CUP]
COMPETITIONS = CONMEBOL-Copa Libertadores
LF_SELECTOR_STANDING = div.module-standing
;TODO Create selectors to home and away standings
;TODO Create selectors to next rounds

[CONTINENTAL-LIGA-CUP]
COMPETITIONS = UEFA-Champions League
LF_SELECTOR_STANDING = div.module-standing
;TODO Create selectors to home and away standings
;TODO Create selectors to next rounds