[TELEGRAM]
TOKEN = 8319194344:AAHPeyUIF4U8jY0jIlkCAycR8dOITvT5TqA
CHAT_ID = -5132072076

;[EMAIL]
;SMTP_SERVER = smtp.gmail.com
;SMTP_PORT = 587
;USERNAME = miguel.arcos.trader@gmail.com
;PASSWORD = ammr sxkn ibxa kmoh
;RECIPIENTS = miguel.arcos.trader@gmail.com